### ISSUE TITLE
Missing Ag.BlogExample?

### ISSUE THREAD

**Issue by bwaidelich** [agitso/event#13]
Hi there ;)

In the "How" section of the main README you refer to "Ag.BlogExample", but I fail to find that package.

**Comment by hmrdk** [comment]
Hi Bastian

I haven't looked at this for a very long time - but try to have a look at: https://github.com/agitso/shop

We are using events a lot in Famly - the approach we use there is very closely related to Ag.Event.

I know Akii and Afoeder are looking into updating Ag.Event.

**Comment by bwaidelich** [comment]
2 minute response time on a weekend, that's what I'd call a good customer support :smile: 

Thanks, Henrik!

**Comment by hmrdk** [comment]
I'm sitting at the Mac working hard to get the last things sorted out for our Famly US launch Wednesday in the coming week. We're launching in a preschool in SF :-)

**Comment by bwaidelich** [comment]
Awesome, good luck with that!
